spring:
  influx:
    enabled: false
    url: http://influxdb.s.cosmoplat.com
    token: BRj_y6Y457NRHFSRcWHi8oOcrRccE5Ho8Ul4zgZw6GFcSqJ2HzR1XrS0YKYjXXI3-jNhYUGAE64XCAfg7uZTAg==
    org: cosmosd
    bucket: him-iot
    password: &3D26hRSLGpINxoU  #用户密码用不上
    user: cosmo