#Spring Boot 2.0配置hikari数据连接池

# jdbc_config   datasource
spring:
  datasource:
#    url: jdbc:mysql://47.105.130.1:3306/genesis?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&zeroDateTimeBehavior=convertToNull
#    username: wzx
#    password: As123456
    url: jdbc:mysql://47.105.130.1:3306/dreamland?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: wzx
    password: As123456
    driverClassName: com.mysql.cj.jdbc.Driver
  # Hikari will use the above plus the following to setup connection pooling
  #Spring Boot 2.0 includes HikariDataSource by default
  #  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    auto-commit: true #autoCommit配置从池返回的连接的默认自动提交行为。默认值为true。
    connection-timeout: 60000 #connectionTimeout是客户端等待连接池连接的最大毫秒数
    minimum-idle: 5 #minimumIdle是HikariCP在连接池中维护的最小空闲连接数
    maximum-pool-size: 50 #maximumPoolSize配置最大池大小
    idle-timeout: 300000 #idleTimeout是允许连接在连接池中空闲的最长时间（以毫秒为单位）
    max-lifetime: 1200000 #maxLifetime是池中连接关闭后的最长生命周期（以毫秒为单位）
    pool-name: DatebookHikariCP
    connection-test-query: SELECT 1
