#debug: true

server:
  port: 8087
  servlet:
    session:
      timeout: 3600
    context-path: /dreamland




#spring  
spring:
  mvc:
    format:
      date: "yyyy-MM-dd HH:mm:ss"
  profiles:
    include: hikari,redis
    active: dev
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
  servlet:
    multipart: #文件上传大小限制
      max-file-size: "10MB"
      maxRequestSize: "100MB"

mybatis-plus:
  mapper-locations: classpath*:mybatis/mapping/**/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zero.dreamland.biz.**.entity  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#pagehelper分页
pagehelper:
  auto-dialect: true
  helper-dialect: mysql
  reasonable: true
  params: count=countSql

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50



