#Redis配置
spring:
  redis:
#    host: 123.206.103.188
    host: 47.105.130.1
    port: 6379
    password: wzx@2020 #根据需要

#    公司45
#    host: 192.168.30.45
#    password: Jbinfo12349@175Aa
#    port: 6539
    timeout: 35000 # 连接超时时间（毫秒）   
    database: 15  # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: -1  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0
    

   